steps:
- uses: actions/checkout@master
- uses: codecov/codecov-action@v1
  with:
    flags: unittests # optional
    fail_ci_if_error: true # optional (default = false)
    verbose: true # optional (default = false)
